### ISSUE TITLE
Tables error

### ISSUE THREAD

**Issue by machour** [machour/git-point-playground#10]
- `v3.root` is the root endpoint
- `v3.parameters()` is the sole responsible for preparing the `fetch()` call parameters. It takes the accessToken **(mandatory)**, the HTTP method *(optional)*, the Accept header  *(optional)* and a body for the request *(optional)*, does its magic, and returns the correct object.
- The rest of the object consist of helpers method using a clear nomenclature : 
       **httpVerb** **AcceptedResult** ()

| > 99 | < 99
| - | - |
| <img src="https://user-images.githubusercontent.com/4408379/30852321-0e821e84-a2b4-11e7-8822-d8a0782fcacd.jpg" width="300" /> | <img src="https://user-images.githubusercontent.com/4408379/30852323-11184b1e-a2b4-11e7-827b-001d75e267da.jpg" width="300" />

**Comment by Antoine38660** [comment]
Woow, it's awesome.

You speak Russian?
