### ISSUE TITLE
Keep it open

### ISSUE THREAD

**Issue by machour** [machour/git-point-playground#2]
Here's the new Nanuto font : 

* **iOS**
<img width=200 alt="simulator screen shot - iphone 6 - 2017-10-01 at 01 06 51" src="https://user-images.githubusercontent.com/9287184/31050235-fde64a02-a644-11e7-95cd-58032c735208.png">  <img width=200 alt="simulator screen shot - iphone 6 - 2017-10-01 at 01 10 43" src="https://user-images.githubusercontent.com/9287184/31050254-7cdee396-a645-11e7-82de-16ed1a2fecaa.png"> <img  width=200 alt="simulator screen shot - iphone 6 - 2017-10-01 at 01 09 07" src="https://user-images.githubusercontent.com/9287184/31050255-7d023468-a645-11e7-91b6-fce9246480c6.png"> <img  width=200 alt="simulator screen shot - iphone 6 - 2017-10-01 at 01 09 03" src="https://user-images.githubusercontent.com/9287184/31050256-7d052c5e-a645-11e7-9e35-879e1a3d7c77.png">

* **Android** (Thanks to @machour ❤️ )
<img width="200" alt="screen shot 2017-10-01 at 1 17 32 am" src="https://user-images.githubusercontent.com/304450/31050577-05d5a0a0-a64f-11e7-8c80-b2562c60f655.png"> <img width="200" alt="screen shot 2017-10-01 at 1 18 29 am" src="https://user-images.githubusercontent.com/304450/31050578-05dac3dc-a64f-11e7-8881-4b57886ed758.png"> <img width="200" alt="screen shot 2017-10-01 at 1 19 12 am" src="https://user-images.githubusercontent.com/304450/31050579-05df7dd2-a64f-11e7-8ff4-9b6ef4997f1f.png">

**Comment by machour** [comment]
It's very easy to make some words **bold** and other words *italic* with Markdown. 
You can even [link to Google!](http://google.com)

Sometimes you want numbered lists:

1. One
2. Two
3. Three

Sometimes you want bullet points:

* Start a line with a star
* Profit!

Alternatively,

- Dashes work just as well
- And if you have sub points, put two spaces before the dash or star:
  - Like this
  - And this

If you want to embed images, this is how you do it:
![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)

# h1
## h2
### h3
#### h4
##### h5
###### h6

If you'd like to quote someone, use the > character before the line:

> Coffee. The finest organic suspension ever devised... I beat the Borg with it.
> - Captain Janeway

There are many different ways to style code with GitHub's markdown. If you have inline code blocks, wrap them in backticks: `var example = true`.  If you've got a longer block of code, you can indent with four spaces:

    if (isAwesome){
      return true
    }

GitHub also supports something called code fencing, which allows for multiple lines without indentation:

```
if (isAwesome){
  return true
}
```

And if you'd like to use syntax highlighting, include the language:

```javascript
if (isAwesome){
  return true
}
```
GitHub supports many extras in Markdown that help you reference and link to people. If you ever want to direct a comment at someone, you can prefix their name with an @ symbol: Hey @kneath — love your sweater!

But I have to admit, tasks lists are my favorite:

- [x] This is a complete item
- [ ] This is an incomplete item

When you include a task list in the first comment of an Issue, you will see a helpful progress bar in your list of issues. It works in Pull Requests, too!

And, of course emoji! :sparkles: :camel: :boom:

**Comment by kernel47** [comment]
Smart is the new sexy :p

**Comment by machour** [comment]
Commenting from GitPoint :100:

**Comment by jouderianjr** [comment]
Test comment 🥇

**Comment by jouderianjr** [comment]
Testagain 💃

**Comment by machour** [comment]
New comment

**Comment by machour** [comment]
New comment with **markdown**

**Comment by machour** [comment]
New new comment with **markdown**

**Comment by machour** [comment]
New **markdown**

**Comment by machour** [comment]
Test new **markdown** !!!!!

**Comment by machour** [comment]
`ok`

**Comment by machour** [comment]
Yes

**Comment by machour** [comment]
`ok`

**Comment by machour** [comment]
Test from **android**

**Comment by machour** [comment]
New **comment**

**Comment by machour** [comment]
New `code`

Ouf **works**
