### ISSUE TITLE
Implementing details in markdown

### ISSUE THREAD

**Issue by machour** [machour/git-point-playground#33]
@ArvinH here's a playground for your tests, so that you can comment as much as you want while keeping your PR clean ;)

Fot test:

#### `<code>` in summary:

<details>
<summary><code>console.log('test');</code></summary>
try something for summary
</details>
  
#### `<image>` in summary:
<details>
<summary><img alt="@ArvinH" class="avatar" height="28" src="https://avatars3.githubusercontent.com/u/286856?s=56&amp;v=4" width="28"></summary>
try something for summary
</details>

#### `<li>` in summary:
<details>
<summary>
<ul><li>test 1</li><li>test2</li></ul>
</summary>
try something for summary
</details>

#### `details` in summary:

<details>
<summary><details>
<summary> Summary as detail 😆 </summary>
nested summary details
</details></summary>
top summary details
</details>

**Comment by ArvinH** [comment]
Awesome! 🏆 
Thanks for doing this, I will keep working on it, stay tuned!

**Comment by ArvinH** [comment]
<details><summary><code>console.log('test2')</code></summary>no new line</details>
<code>console.log('test2')</code>

* one
* two

**Comment by ArvinH** [comment]
<details>
<summary>What if we have tags in hiddenChildren</summary>
<code>console.lot('wow');</code>
<ul>
<li> one</li>
<li>two</li>
</ul>
</details>

**Comment by ArvinH** [comment]
<details>
<summary><ul>
<li> styling </li>
<li> is </li>
<li> hard </li>
</summary>

try something for summary
</details>



<details>
<summary>no details content?
</summary>
</details>

empty `details`?
<details>
</details>

<details>
Let's see
<summary>Does order matter?
</summary>
</details>
